[package]
name = "squirrel"
version = "0.4.0"
description = "A clipboard manager"
keywords = ["clipboard manager"]
# i really dont know if Squirrel falls into any category 
# listed at https://crates.io/category_slugs
categories = ["accessibility"] 
repository = "https://github.com/Koei32/squirrel"
readme = "../../README.md"
license = "GPL-3.0-only"
authors = ["Koei"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
active-win-pos-rs = "0.11.0"
anyhow = "1.0.102"
base64 = "0.23.0"
chrono = "0.4.44"
clipboard-rs = "0.3.4"
dirs = "6.0.0"
enigo = "0.6.1"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "macros"] }
sysinfo = "0.39.5"
tauri = {  version = "2.0.0", features = [ "tray-icon", "image-png" ] }
tauri-plugin-opener = "2"
tauri-plugin-prevent-default = "5"
tokio = { version="1.52.3", features = ["macros"] }
toml = "1.1.4"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
