name: Build

on:
    push:
        branches: ["ci-test"]

jobs:
    build-win:
        name: Windows build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run tauri build
            - uses: actions/upload-artifact@v7
              with:
                  name: builds
                  path: |
                      src-tauri/target/release/squirrel.exe
                      src-tauri/target/release/bundle
    build-lin:
        name: Linux build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Install Ubuntu specific deps
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run tauri build
            - uses: actions/upload-artifact@v7
              with:
                  name: builds
                  path: |
                      src-tauri/target/release/squirrel
                      src-tauri/target/release/bundle/appimage/squirrel*.AppImage
                      src-tauri/target/release/bundle/deb/squirrel*.deb
                      src-tauri/target/release/bundle/rpm/squirrel*.rpm
