name: "PR Lint (backend)"

on:
    pull_request:
        branches: ["master"]
        paths:
            - src-tauri/**

jobs:
    backend-lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src-tauri
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy
            - name: Install ubuntu specific deps
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils
            - name: Clippy
              run: cargo clippy
